document.write("<div class=\"menu\">");
document.write("		<ul class=\"dmx l\">");
document.write("			<li>");
document.write("				<a href=\"https:\/\/www.museneko.top\/\"><img src=\"https:\/\/www.museneko.top\/mn.ico\" width=\"25\" height=\"25\"><\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/www.museneko.top\/\">首页<\/a><\/li>");
document.write("			<li class=\"nav\">");
document.write("				<a href=\"https:\/\/www.museneko.top\/animation\">缪斯NEKO动漫<\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/www.museneko.top\/movie\">缪斯NEKO影视<\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/www.museneko.top\/comic\">缪斯NEKO漫画<\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/www.museneko.top\/ecy\">二次元图库<\/a><\/li>");
document.write("    <\/ul>");
document.write("<ul class=\"dme r\">");
document.write("			<li>");
document.write("<a href=\"https:\/\/bbs.museneko.top\" >缪斯NEKO论坛<\/a>");
document.write("			<\/li>");
document.write("			<li>");
document.write("<a href=\"https:\/\/www.museneko.top\/MUSENEKO\" >缪斯NEKO官方<\/a>");
document.write("			<\/li>");
document.write("			<li>");
document.write("<a href=\"https:\/\/www.museneko.top\/muse\" >缪斯NEKO专区<\/a>");
document.write("			<\/li>");
document.write("    <\/div>");
document.write("	<br>");