document.write("	<div class=\"menu\">");
document.write("		<ul class=\"dmx l\">");
document.write("			<li>");
document.write("				<a href=\"https:\/\/www.museneko.top\/\"><img src=\"https:\/\/www.museneko.top\/mn.ico\" width=\"25\" height=\"25\"><\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/www.museneko.top\/\">首页<\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/www.museneko.top\/animation\">缪斯喵动漫<\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/www.museneko.top\/movie\">缪斯喵影视<\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/www.museneko.top\/comic\">缪斯喵漫画<\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/www.museneko.top\/ecy\">二次元图库<\/a><\/li>");
document.write("    <\/ul>");
document.write("<ul class=\"dme r\">");
document.write("			<li>");
document.write("<a href=\"https:\/\/game.museneko.top\" >缪斯喵游戏<\/a>");
document.write("			<\/li>");
document.write("			<li class=\"nav\">");
document.write("<a href=\"https:\/\/www.museneko.top\/MUSENEKO\" >缪斯喵官方<\/a>");
document.write("			<\/li>");
document.write("			<li>");
document.write("<a href=\"https:\/\/www.museneko.top\/muse\" >缪斯喵专区<\/a>");
document.write("			<\/li>");
document.write("    <\/div>");
document.write("	<br>");