document.write("	        <ul class=\"top_nav clearfix\">");
document.write("                				<li class=\"active\"><a href=\"https:\/\/www.museneko.top\/animation\" >缪斯喵动漫<\/a><\/li>");
document.write("			<\/ul>");
document.write("		<\/div>");
document.write("		<div class=\"head_user\">");
document.write("		    <ul>");
document.write("	        	<li><a href=\"https:\/\/www.museneko.top\/main\"><font size=\"1\">首页<\/font><\/a><\/li>");
document.write("                <li><a href=\"https:\/\/www.museneko.top\/animation\" ><font size=\"1\">缪斯喵动漫<\/font><\/a><\/li>");
document.write("                <li><a href=\"https:\/\/www.museneko.top\/movie\" ><font size=\"1\">缪斯喵影视<\/font><\/a><\/li>");
document.write("                <li><a href=\"https:\/\/www.museneko.top\/comic\" ><font size=\"1\">缪斯喵漫画<\/font><\/a><\/li>");
document.write("                <li><a href=\"https:\/\/www.museneko.top\/ecy\" ><font size=\"1\">二次元图库<\/font><\/a><\/li>");
document.write("				<li><a href=\"https:\/\/game.museneko.top\" ><font size=\"1\">缪斯喵游戏<\/font><\/a><\/li>");
document.write("				<li><a href=\"https:\/\/www.museneko.top\/MUSENEKO\" ><font size=\"1\">缪斯喵官方<\/font><\/a><\/li>");
document.write("                            <\/ul>");